/**
 * This code was generated by Builder.io.
 */
import React from "react";

function Header() {
  return (
    <header className="relative w-full max-w-[842px]">
      <img
        loading="lazy"
        src="https://cdn.builder.io/api/v1/image/assets/TEMP/ddca89819090cfe0f92d20e459dbfea6610bc689676e938f391d484c2891a995?apiKey=95bdd6893dbc47d0ac51c502bd26afe2&"
        alt="Company logo"
        className="max-w-full aspect-[3.57] w-[344px]"
      />
    </header>
  );
}

export default Header;
